In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('Recommend.csv',names=['user_id','movie_id','rating','timestamp'])
data.head()

user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [6]:
from sklearn.model_selection import train_test_split
n_users = data.user_id.unique().shape[0]
n_movies = data.movie_id.unique().shape[0]
train,test = train_test_split(data,test_size=0.25)

In [8]:
train_matrix = np.zeros((n_users,n_movies))
for line in train.itertuples():
    train_matrix[line[1]-1,line[2]-1] = line[3]
train_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [9]:
test_matrix = np.zeros((n_users,n_movies))
for line in test.itertuples():
    test_matrix[line[1]-1,line[2]-1] = line[3]
test_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_matrix,metric='cosine')
movie_similarity = pairwise_distances(train_matrix.T,metric='cosine')
mean_user_rating = train_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff = train_matrix - mean_user_rating
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T

user_pred

array([[ 1.57878529,  0.59078078,  0.4598111 , ...,  0.28390109,
         0.2836901 ,  0.28374363],
       [ 1.32449522,  0.3203506 ,  0.13863091, ..., -0.06616786,
        -0.06484432, -0.06452616],
       [ 1.35801868,  0.29409709,  0.11902642, ..., -0.09233601,
        -0.09048113, -0.09021666],
       ...,
       [ 1.19783887,  0.24680644,  0.07290557, ..., -0.12121345,
        -0.12065368, -0.12027921],
       [ 1.37995745,  0.35540549,  0.20859895, ...,  0.00697695,
         0.00758026,  0.00783945],
       [ 1.42329935,  0.42079705,  0.29846504, ...,  0.12223261,
         0.12201411,  0.12209607]])